#!/usr/bin/env python

import sys
import mutagen.mp4

file = mutagen.mp4.MP4(sys.argv[1])

if not file.has_key('covr'):
    print("File has no cover art.")
    exit()
#end

covers = file['covr']

if len(covers) == 0:
    print("File has no cover art.")
    exit()
elif len(covers) > 1:
    print("Warning, file has multiple covers, using the first.")
#end

cover = covers[0]

if cover.imageformat == 13:
    print("JPEG cover found")
    ext = ".jpg"
elif cover.imageformat == 14:
    print("PNG cover found")
    ext = ".png"
#end

f = open('cover'+ext, 'w')
f.write(cover)
