#!/opt/local/bin/python

import os
import json
from gmusicapi import Musicmanager

record_fname = "upload_record.json"

files_to_upload = []
fails = []

def write_record():
    json.dump(uploaded, open(record_fname, 'w'))
#end

if(os.path.isfile(record_fname)):
    f = open(record_fname, 'r')
    uploaded = json.load(f)
else:
    uploaded = {}
#end

for folder, _subs, files in os.walk('.', followlinks=True):
    print("Scanning folder " + folder)
    for file in files:
        if file.endswith('.mp3') or file.endswith('.flac'):
            files_to_upload.append(os.path.join(folder, file))
        #end
    #end
#end

print("Files found: ")
for file in files_to_upload:
    print(file)
#end

manager = Musicmanager();

if not manager.login():
    print("login failed!")
    exit()
#end

def process_uploads():
    for music_file in files_to_upload:
        if music_file in uploaded:
            print(music_file + " has already been uploaded.")
            continue
        #end            
        print("Uploading " + music_file)
        if manager.upload(music_file):
            print("Uploaded " + music_file)
            uploaded[music_file] = "true"
        else:
            fails.append(music_file)
        #end
    #end
#end

def print_fails():
    if fails:
        print("The follow files failed to upload: ")
        for file in fails:
            print(file)
        #end
    #end
#end

try:
    process_uploads()
except KeyboardInterrupt:
    print("Keyboard interrupt, quitting...")
finally:
    write_record()
#end
