#!/opt/local/bin/python

import os
from gmusicapi import Musicmanager

files_to_upload = []

fails = []

for folder, _subs, files in os.walk('.', followlinks=True):
    print("Scanning folder " + folder)
    for file in files:
        if file.endswith('.mp3') or file.endswith('.flac'):
            files_to_upload.append(os.path.join(folder, file))
        #end
    #end
#end

print("Files found: ")
for file in files_to_upload:
    print(file)
#end

manager = Musicmanager();

if not manager.login():
    print("login failed!")
    exit()
#end

for music_file in files_to_upload:
    print("Uploading " + music_file)
    if manager.upload(music_file):
        print("Uploaded " + music_file)
    else:
        fails.append(music_file)
    #end
#end

if fails:
    print("The follow files failed to upload: ")
    for file in fails:
        print(file)
    #end
#end